# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img2epub.ui'
#
# Created: Tue Nov 09 22:51:40 2010
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DialogImg2Epub(object):
    def setupUi(self, DialogImg2Epub):
        DialogImg2Epub.setObjectName("DialogImg2Epub")
        DialogImg2Epub.resize(480, 600)
        self.gridLayout = QtGui.QGridLayout(DialogImg2Epub)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtGui.QProgressBar(DialogImg2Epub)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.pushButtonRun = QtGui.QPushButton(DialogImg2Epub)
        self.pushButtonRun.setEnabled(False)
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.gridLayout.addWidget(self.pushButtonRun, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(DialogImg2Epub)
        self.tabWidget.setObjectName("tabWidget")
        self.tabEpub = QtGui.QWidget()
        self.tabEpub.setObjectName("tabEpub")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEpub)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxTitle = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxTitle.sizePolicy().hasHeightForWidth())
        self.groupBoxTitle.setSizePolicy(sizePolicy)
        self.groupBoxTitle.setObjectName("groupBoxTitle")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBoxTitle)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditTitle = QtGui.QLineEdit(self.groupBoxTitle)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.horizontalLayout_4.addWidget(self.lineEditTitle)
        self.gridLayout_2.addWidget(self.groupBoxTitle, 0, 0, 1, 2)
        self.groupBoxCreator = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxCreator.sizePolicy().hasHeightForWidth())
        self.groupBoxCreator.setSizePolicy(sizePolicy)
        self.groupBoxCreator.setObjectName("groupBoxCreator")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBoxCreator)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditCreator = QtGui.QLineEdit(self.groupBoxCreator)
        self.lineEditCreator.setObjectName("lineEditCreator")
        self.horizontalLayout_5.addWidget(self.lineEditCreator)
        self.gridLayout_2.addWidget(self.groupBoxCreator, 1, 0, 1, 2)
        self.groupBoxPublisher = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPublisher.sizePolicy().hasHeightForWidth())
        self.groupBoxPublisher.setSizePolicy(sizePolicy)
        self.groupBoxPublisher.setObjectName("groupBoxPublisher")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBoxPublisher)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditPublisher = QtGui.QLineEdit(self.groupBoxPublisher)
        self.lineEditPublisher.setObjectName("lineEditPublisher")
        self.horizontalLayout_6.addWidget(self.lineEditPublisher)
        self.gridLayout_2.addWidget(self.groupBoxPublisher, 2, 0, 1, 1)
        self.groupBoxDate = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxDate.sizePolicy().hasHeightForWidth())
        self.groupBoxDate.setSizePolicy(sizePolicy)
        self.groupBoxDate.setObjectName("groupBoxDate")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBoxDate)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditDate = QtGui.QLineEdit(self.groupBoxDate)
        self.lineEditDate.setObjectName("lineEditDate")
        self.horizontalLayout_7.addWidget(self.lineEditDate)
        self.gridLayout_2.addWidget(self.groupBoxDate, 2, 1, 1, 1)
        self.groupBoxSubject = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSubject.sizePolicy().hasHeightForWidth())
        self.groupBoxSubject.setSizePolicy(sizePolicy)
        self.groupBoxSubject.setObjectName("groupBoxSubject")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBoxSubject)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditSubject = QtGui.QLineEdit(self.groupBoxSubject)
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.horizontalLayout_8.addWidget(self.lineEditSubject)
        self.gridLayout_2.addWidget(self.groupBoxSubject, 3, 0, 1, 1)
        self.groupBoxLanguage = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxLanguage.sizePolicy().hasHeightForWidth())
        self.groupBoxLanguage.setSizePolicy(sizePolicy)
        self.groupBoxLanguage.setObjectName("groupBoxLanguage")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBoxLanguage)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEditLanguage = QtGui.QLineEdit(self.groupBoxLanguage)
        self.lineEditLanguage.setObjectName("lineEditLanguage")
        self.horizontalLayout_11.addWidget(self.lineEditLanguage)
        self.gridLayout_2.addWidget(self.groupBoxLanguage, 3, 1, 1, 1)
        self.groupBoxType = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxType.sizePolicy().hasHeightForWidth())
        self.groupBoxType.setSizePolicy(sizePolicy)
        self.groupBoxType.setObjectName("groupBoxType")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBoxType)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEditType = QtGui.QLineEdit(self.groupBoxType)
        self.lineEditType.setObjectName("lineEditType")
        self.horizontalLayout_9.addWidget(self.lineEditType)
        self.gridLayout_2.addWidget(self.groupBoxType, 4, 0, 1, 2)
        self.groupBoxUUID = QtGui.QGroupBox(self.tabEpub)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxUUID.sizePolicy().hasHeightForWidth())
        self.groupBoxUUID.setSizePolicy(sizePolicy)
        self.groupBoxUUID.setObjectName("groupBoxUUID")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBoxUUID)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditUUID = QtGui.QLineEdit(self.groupBoxUUID)
        self.lineEditUUID.setObjectName("lineEditUUID")
        self.horizontalLayout_3.addWidget(self.lineEditUUID)
        self.pushButtonUUID = QtGui.QPushButton(self.groupBoxUUID)
        self.pushButtonUUID.setObjectName("pushButtonUUID")
        self.horizontalLayout_3.addWidget(self.pushButtonUUID)
        self.gridLayout_2.addWidget(self.groupBoxUUID, 5, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 42, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabEpub, "")
        self.tabFiles = QtGui.QWidget()
        self.tabFiles.setObjectName("tabFiles")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabFiles)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBoxInputs = QtGui.QGroupBox(self.tabFiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxInputs.sizePolicy().hasHeightForWidth())
        self.groupBoxInputs.setSizePolicy(sizePolicy)
        self.groupBoxInputs.setObjectName("groupBoxInputs")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBoxInputs)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditInputs = QtGui.QLineEdit(self.groupBoxInputs)
        self.lineEditInputs.setObjectName("lineEditInputs")
        self.horizontalLayout_2.addWidget(self.lineEditInputs)
        self.toolButtonInputs = QtGui.QToolButton(self.groupBoxInputs)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/img-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonInputs.setIcon(icon)
        self.toolButtonInputs.setObjectName("toolButtonInputs")
        self.horizontalLayout_2.addWidget(self.toolButtonInputs)
        self.toolButtonInputDir = QtGui.QToolButton(self.groupBoxInputs)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/diropen-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonInputDir.setIcon(icon1)
        self.toolButtonInputDir.setObjectName("toolButtonInputDir")
        self.horizontalLayout_2.addWidget(self.toolButtonInputDir)
        self.verticalLayout_2.addWidget(self.groupBoxInputs)
        self.groupBoxOutput = QtGui.QGroupBox(self.tabFiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxOutput.sizePolicy().hasHeightForWidth())
        self.groupBoxOutput.setSizePolicy(sizePolicy)
        self.groupBoxOutput.setObjectName("groupBoxOutput")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBoxOutput)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditOutput = QtGui.QLineEdit(self.groupBoxOutput)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.horizontalLayout.addWidget(self.lineEditOutput)
        self.toolButtonOutput = QtGui.QToolButton(self.groupBoxOutput)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/epub-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonOutput.setIcon(icon2)
        self.toolButtonOutput.setObjectName("toolButtonOutput")
        self.horizontalLayout.addWidget(self.toolButtonOutput)
        self.verticalLayout_2.addWidget(self.groupBoxOutput)
        self.groupBoxFiles = QtGui.QGroupBox(self.tabFiles)
        self.groupBoxFiles.setObjectName("groupBoxFiles")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBoxFiles)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidgetFiles = QtGui.QTreeWidget(self.groupBoxFiles)
        self.treeWidgetFiles.setObjectName("treeWidgetFiles")
        self.verticalLayout.addWidget(self.treeWidgetFiles)
        self.verticalLayout_2.addWidget(self.groupBoxFiles)
        self.tabWidget.addTab(self.tabFiles, "")
        self.tabImageSettings = QtGui.QWidget()
        self.tabImageSettings.setObjectName("tabImageSettings")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabImageSettings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBoxISGOO = QtGui.QGroupBox(self.tabImageSettings)
        self.groupBoxISGOO.setObjectName("groupBoxISGOO")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBoxISGOO)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelWidth = QtGui.QLabel(self.groupBoxISGOO)
        self.labelWidth.setObjectName("labelWidth")
        self.horizontalLayout_10.addWidget(self.labelWidth)
        self.spinBoxWidth = QtGui.QSpinBox(self.groupBoxISGOO)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxWidth.sizePolicy().hasHeightForWidth())
        self.spinBoxWidth.setSizePolicy(sizePolicy)
        self.spinBoxWidth.setMinimumSize(QtCore.QSize(61, 0))
        self.spinBoxWidth.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBoxWidth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxWidth.setMinimum(16)
        self.spinBoxWidth.setMaximum(9999)
        self.spinBoxWidth.setSingleStep(10)
        self.spinBoxWidth.setProperty("value", 580)
        self.spinBoxWidth.setObjectName("spinBoxWidth")
        self.horizontalLayout_10.addWidget(self.spinBoxWidth)
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.labelHeight = QtGui.QLabel(self.groupBoxISGOO)
        self.labelHeight.setObjectName("labelHeight")
        self.horizontalLayout_10.addWidget(self.labelHeight)
        self.spinBoxHeight = QtGui.QSpinBox(self.groupBoxISGOO)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxHeight.sizePolicy().hasHeightForWidth())
        self.spinBoxHeight.setSizePolicy(sizePolicy)
        self.spinBoxHeight.setMinimumSize(QtCore.QSize(61, 0))
        self.spinBoxHeight.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBoxHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxHeight.setMinimum(16)
        self.spinBoxHeight.setMaximum(9999)
        self.spinBoxHeight.setSingleStep(10)
        self.spinBoxHeight.setProperty("value", 750)
        self.spinBoxHeight.setObjectName("spinBoxHeight")
        self.horizontalLayout_10.addWidget(self.spinBoxHeight)
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.labelColors = QtGui.QLabel(self.groupBoxISGOO)
        self.labelColors.setObjectName("labelColors")
        self.horizontalLayout_10.addWidget(self.labelColors)
        self.spinBoxColors = QtGui.QSpinBox(self.groupBoxISGOO)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxColors.sizePolicy().hasHeightForWidth())
        self.spinBoxColors.setSizePolicy(sizePolicy)
        self.spinBoxColors.setMinimumSize(QtCore.QSize(61, 0))
        self.spinBoxColors.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBoxColors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxColors.setMinimum(2)
        self.spinBoxColors.setMaximum(256)
        self.spinBoxColors.setSingleStep(1)
        self.spinBoxColors.setProperty("value", 16)
        self.spinBoxColors.setObjectName("spinBoxColors")
        self.horizontalLayout_10.addWidget(self.spinBoxColors)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.checkBoxDither = QtGui.QCheckBox(self.groupBoxISGOO)
        self.checkBoxDither.setObjectName("checkBoxDither")
        self.verticalLayout_4.addWidget(self.checkBoxDither)
        self.verticalLayout_5.addWidget(self.groupBoxISGOO)
        self.groupBoxISCO = QtGui.QGroupBox(self.tabImageSettings)
        self.groupBoxISCO.setObjectName("groupBoxISCO")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBoxISCO)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButtonCut0 = QtGui.QRadioButton(self.groupBoxISCO)
        self.radioButtonCut0.setChecked(True)
        self.radioButtonCut0.setObjectName("radioButtonCut0")
        self.verticalLayout_3.addWidget(self.radioButtonCut0)
        self.radioButtonCutA = QtGui.QRadioButton(self.groupBoxISCO)
        self.radioButtonCutA.setObjectName("radioButtonCutA")
        self.verticalLayout_3.addWidget(self.radioButtonCutA)
        self.radioButtonCutH = QtGui.QRadioButton(self.groupBoxISCO)
        self.radioButtonCutH.setObjectName("radioButtonCutH")
        self.verticalLayout_3.addWidget(self.radioButtonCutH)
        self.radioButtonCutR = QtGui.QRadioButton(self.groupBoxISCO)
        self.radioButtonCutR.setObjectName("radioButtonCutR")
        self.verticalLayout_3.addWidget(self.radioButtonCutR)
        self.radioButtonCutV = QtGui.QRadioButton(self.groupBoxISCO)
        self.radioButtonCutV.setObjectName("radioButtonCutV")
        self.verticalLayout_3.addWidget(self.radioButtonCutV)
        self.verticalLayout_5.addWidget(self.groupBoxISCO)
        self.groupBoxISTO = QtGui.QGroupBox(self.tabImageSettings)
        self.groupBoxISTO.setObjectName("groupBoxISTO")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxISTO)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxTrim = QtGui.QCheckBox(self.groupBoxISTO)
        self.checkBoxTrim.setChecked(True)
        self.checkBoxTrim.setObjectName("checkBoxTrim")
        self.gridLayout_3.addWidget(self.checkBoxTrim, 0, 0, 1, 2)
        self.labelTrimValue = QtGui.QLabel(self.groupBoxISTO)
        self.labelTrimValue.setObjectName("labelTrimValue")
        self.gridLayout_3.addWidget(self.labelTrimValue, 1, 0, 1, 1)
        self.spinBoxTrimValue = QtGui.QSpinBox(self.groupBoxISTO)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxTrimValue.sizePolicy().hasHeightForWidth())
        self.spinBoxTrimValue.setSizePolicy(sizePolicy)
        self.spinBoxTrimValue.setMinimumSize(QtCore.QSize(61, 0))
        self.spinBoxTrimValue.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBoxTrimValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTrimValue.setMinimum(0)
        self.spinBoxTrimValue.setMaximum(100)
        self.spinBoxTrimValue.setSingleStep(10)
        self.spinBoxTrimValue.setProperty("value", 20)
        self.spinBoxTrimValue.setObjectName("spinBoxTrimValue")
        self.gridLayout_3.addWidget(self.spinBoxTrimValue, 1, 1, 1, 1)
        self.labelTrimIter = QtGui.QLabel(self.groupBoxISTO)
        self.labelTrimIter.setObjectName("labelTrimIter")
        self.gridLayout_3.addWidget(self.labelTrimIter, 2, 0, 1, 1)
        self.spinBoxTrimIter = QtGui.QSpinBox(self.groupBoxISTO)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxTrimIter.sizePolicy().hasHeightForWidth())
        self.spinBoxTrimIter.setSizePolicy(sizePolicy)
        self.spinBoxTrimIter.setMinimumSize(QtCore.QSize(61, 0))
        self.spinBoxTrimIter.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBoxTrimIter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTrimIter.setMinimum(1)
        self.spinBoxTrimIter.setMaximum(100)
        self.spinBoxTrimIter.setSingleStep(1)
        self.spinBoxTrimIter.setProperty("value", 2)
        self.spinBoxTrimIter.setObjectName("spinBoxTrimIter")
        self.gridLayout_3.addWidget(self.spinBoxTrimIter, 2, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBoxISTO)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.tabImageSettings, "")
        self.tabMessageLog = QtGui.QWidget()
        self.tabMessageLog.setObjectName("tabMessageLog")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabMessageLog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEditMessageLog = QtGui.QTextEdit(self.tabMessageLog)
        self.textEditMessageLog.setReadOnly(True)
        self.textEditMessageLog.setObjectName("textEditMessageLog")
        self.verticalLayout_6.addWidget(self.textEditMessageLog)
        self.tabWidget.addTab(self.tabMessageLog, "")
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabAbout)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser = QtGui.QTextBrowser(self.tabAbout)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAbout, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(DialogImg2Epub)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBoxTrim, QtCore.SIGNAL("toggled(bool)"), self.spinBoxTrimValue.setEnabled)
        QtCore.QObject.connect(self.checkBoxTrim, QtCore.SIGNAL("toggled(bool)"), self.spinBoxTrimIter.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogImg2Epub)
        DialogImg2Epub.setTabOrder(self.lineEditTitle, self.lineEditCreator)
        DialogImg2Epub.setTabOrder(self.lineEditCreator, self.lineEditPublisher)
        DialogImg2Epub.setTabOrder(self.lineEditPublisher, self.lineEditDate)
        DialogImg2Epub.setTabOrder(self.lineEditDate, self.lineEditSubject)
        DialogImg2Epub.setTabOrder(self.lineEditSubject, self.lineEditType)
        DialogImg2Epub.setTabOrder(self.lineEditType, self.pushButtonUUID)
        DialogImg2Epub.setTabOrder(self.pushButtonUUID, self.lineEditUUID)
        DialogImg2Epub.setTabOrder(self.lineEditUUID, self.toolButtonInputs)
        DialogImg2Epub.setTabOrder(self.toolButtonInputs, self.lineEditInputs)
        DialogImg2Epub.setTabOrder(self.lineEditInputs, self.toolButtonOutput)
        DialogImg2Epub.setTabOrder(self.toolButtonOutput, self.lineEditOutput)
        DialogImg2Epub.setTabOrder(self.lineEditOutput, self.pushButtonRun)
        DialogImg2Epub.setTabOrder(self.pushButtonRun, self.spinBoxWidth)
        DialogImg2Epub.setTabOrder(self.spinBoxWidth, self.spinBoxHeight)
        DialogImg2Epub.setTabOrder(self.spinBoxHeight, self.spinBoxColors)
        DialogImg2Epub.setTabOrder(self.spinBoxColors, self.checkBoxDither)
        DialogImg2Epub.setTabOrder(self.checkBoxDither, self.radioButtonCut0)
        DialogImg2Epub.setTabOrder(self.radioButtonCut0, self.radioButtonCutA)
        DialogImg2Epub.setTabOrder(self.radioButtonCutA, self.radioButtonCutH)
        DialogImg2Epub.setTabOrder(self.radioButtonCutH, self.radioButtonCutR)
        DialogImg2Epub.setTabOrder(self.radioButtonCutR, self.radioButtonCutV)
        DialogImg2Epub.setTabOrder(self.radioButtonCutV, self.checkBoxTrim)
        DialogImg2Epub.setTabOrder(self.checkBoxTrim, self.spinBoxTrimValue)
        DialogImg2Epub.setTabOrder(self.spinBoxTrimValue, self.spinBoxTrimIter)
        DialogImg2Epub.setTabOrder(self.spinBoxTrimIter, self.tabWidget)

    def retranslateUi(self, DialogImg2Epub):
        DialogImg2Epub.setWindowTitle(QtGui.QApplication.translate("DialogImg2Epub", "Img2Epub", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRun.setText(QtGui.QApplication.translate("DialogImg2Epub", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxTitle.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxCreator.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditCreator.setText(QtGui.QApplication.translate("DialogImg2Epub", "Img2Epub", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxPublisher.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPublisher.setText(QtGui.QApplication.translate("DialogImg2Epub", "Img2Epub", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxDate.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSubject.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Subject", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSubject.setText(QtGui.QApplication.translate("DialogImg2Epub", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxLanguage.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxType.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditType.setText(QtGui.QApplication.translate("DialogImg2Epub", "Manga, Comics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxUUID.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "UUID", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditUUID.setInputMask(QtGui.QApplication.translate("DialogImg2Epub", "HHHHHHHH-HHHH-HHHH-HHHH-HHHHHHHHHHHH; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditUUID.setText(QtGui.QApplication.translate("DialogImg2Epub", "00000000-0000-0000-0000-000000000000", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUUID.setText(QtGui.QApplication.translate("DialogImg2Epub", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEpub), QtGui.QApplication.translate("DialogImg2Epub", "epub Propeties", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxInputs.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditInputs.setToolTip(QtGui.QApplication.translate("DialogImg2Epub", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">\'|\' separated list of images, directories or archives (CBR, CBZ, ...)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonInputs.setText(QtGui.QApplication.translate("DialogImg2Epub", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonInputDir.setText(QtGui.QApplication.translate("DialogImg2Epub", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxOutput.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditOutput.setToolTip(QtGui.QApplication.translate("DialogImg2Epub", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">epub output file name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOutput.setText(QtGui.QApplication.translate("DialogImg2Epub", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxFiles.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetFiles.headerItem().setText(0, QtGui.QApplication.translate("DialogImg2Epub", "Selected Images", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFiles), QtGui.QApplication.translate("DialogImg2Epub", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxISGOO.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "General Images Output Options", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWidth.setText(QtGui.QApplication.translate("DialogImg2Epub", "Width : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHeight.setText(QtGui.QApplication.translate("DialogImg2Epub", "Height : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelColors.setText(QtGui.QApplication.translate("DialogImg2Epub", "Colors : ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDither.setText(QtGui.QApplication.translate("DialogImg2Epub", "Activate Dithering", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxISCO.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Cutting options", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCut0.setText(QtGui.QApplication.translate("DialogImg2Epub", "No Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCutA.setText(QtGui.QApplication.translate("DialogImg2Epub", "Cut All images in Two", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCutH.setText(QtGui.QApplication.translate("DialogImg2Epub", "Cut only if width > height", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCutR.setText(QtGui.QApplication.translate("DialogImg2Epub", "Cut only if width > height and switch the two images", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonCutV.setText(QtGui.QApplication.translate("DialogImg2Epub", "Cut only if width < height", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxISTO.setTitle(QtGui.QApplication.translate("DialogImg2Epub", "Border Trimming Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTrim.setText(QtGui.QApplication.translate("DialogImg2Epub", "Trimming Enabled", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTrimValue.setText(QtGui.QApplication.translate("DialogImg2Epub", "Value : ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTrimIter.setText(QtGui.QApplication.translate("DialogImg2Epub", "Iterations : ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImageSettings), QtGui.QApplication.translate("DialogImg2Epub", "Image Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMessageLog), QtGui.QApplication.translate("DialogImg2Epub", "Message Log", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("DialogImg2Epub", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Img2EPub</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Convert images into epub documents</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New,courier\'; font-size:8pt;\">Copyright (C) 2010 </span><span style=\" font-size:8pt;\">Stany MARCEL&lt;stanypub@gmail.com&gt;</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://code.google.com/p/img2epub/\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">http://code.google.com/p/img2epub/</span></a></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">GNU GENERAL PUBLIC LICENSE</span></a></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Version 2, June 1991 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Copyright (C) 1989, 1991 Free Software Foundation, Inc. 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"preamble\"></a><a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html#TOC2\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">P</span></a><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">reamble</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The licenses for most software are designed to take away your freedom to share and change it. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change free software--to make sure the software is free for all its users. This General Public License applies to most of the Free Software Foundation\'s software and to any other program whose authors commit to using it. (Some other Free Software Foundation software is covered by the GNU Lesser General Public License instead.) You can apply it to your programs, too. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed to make sure that you have the freedom to distribute copies of free software (and charge for this service if you wish), that you receive source code or can get it if you want it, that you can change the software or use pieces of it in new free programs; and that you know you can do these things. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">To protect your rights, we need to make restrictions that forbid anyone to deny you these rights or to ask you to surrender the rights. These restrictions translate to certain responsibilities for you if you distribute copies of the software, or if you modify it. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">For example, if you distribute copies of such a program, whether gratis or for a fee, you must give the recipients all the rights that you have. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">We protect your rights with two steps: (1) copyright the software, and (2) offer you this license which gives you legal permission to copy, distribute and/or modify the software. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Also, for each author\'s protection and ours, we want to make certain that everyone understands that there is no warranty for this free software. If the software is modified by someone else and passed on, we want its recipients to know that what they have is not the original, so that any problems introduced by others will not reflect on the original authors\' reputations. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Finally, any free program is threatened constantly by software patents. We wish to avoid the danger that redistributors of a free program will individually obtain patent licenses, in effect making the program proprietary. To prevent this, we have made it clear that any patent must be licensed for everyone\'s free use or not licensed at all. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The precise terms and conditions for copying, distribution and modification follow. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"terms\"></a><a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html#TOC3\"><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">T</span></a><span style=\" font-size:8pt; font-weight:600; text-decoration: underline; color:#0000ff;\">ERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">0.</span><span style=\" font-size:8pt;\"> This License applies to any program or other work which contains a notice placed by the copyright holder saying it may be distributed under the terms of this General Public License. The &quot;Program&quot;, below, refers to any such program or work, and a &quot;work based on the Program&quot; means either the Program or any derivative work under copyright law: that is to say, a work containing the Program or a portion of it, either verbatim or with modifications and/or translated into another language. (Hereinafter, translation is included without limitation in the term &quot;modification&quot;.) Each licensee is addressed as &quot;you&quot;. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Activities other than copying, distribution and modification are not covered by this License; they are outside its scope. The act of running the Program is not restricted, and the output from the Program is covered only if its contents constitute a work based on the Program (independent of having been made by running the Program). Whether that is true depends on what the Program does. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">1.</span><span style=\" font-size:8pt;\"> You may copy and distribute verbatim copies of the Program\'s source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and give any other recipients of the Program a copy of this License along with the Program. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">You may charge a fee for the physical act of transferring a copy, and you may at your option offer warranty protection in exchange for a fee. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">2.</span><span style=\" font-size:8pt;\"> You may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions: </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">a)</span><span style=\" font-size:8pt;\"> You must cause the modified files to carry prominent notices stating that you changed the files and the date of any change. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">b)</span><span style=\" font-size:8pt;\"> You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:8px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">c)</span><span style=\" font-size:8pt;\"> If the modified program normally reads commands interactively when run, you must cause it, when started running for such interactive use in the most ordinary way, to print or display an announcement including an appropriate copyright notice and a notice that there is no warranty (or else, saying that you provide a warranty) and that users may redistribute the program under these conditions, and telling the user how to view a copy of this License. (Exception: if the Program itself is interactive but does not normally print such an announcement, your work based on the Program is not required to print an announcement.) </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">These requirements apply to the modified work as a whole. If identifiable sections of that work are not derived from the Program, and can be reasonably considered independent and separate works in themselves, then this License, and its terms, do not apply to those sections when you distribute them as separate works. But when you distribute the same sections as part of a whole which is a work based on the Program, the distribution of the whole must be on the terms of this License, whose permissions for other licensees extend to the entire whole, and thus to each and every part regardless of who wrote it. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Thus, it is not the intent of this section to claim rights or contest your rights to work written entirely by you; rather, the intent is to exercise the right to control the distribution of derivative or collective works based on the Program. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">In addition, mere aggregation of another work not based on the Program with the Program (or with a work based on the Program) on a volume of a storage or distribution medium does not bring the other work under the scope of this License. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">3.</span><span style=\" font-size:8pt;\"> You may copy and distribute the Program (or a work based on it, under Section 2) in object code or executable form under the terms of Sections 1 and 2 above provided that you also do one of the following: </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">a)</span><span style=\" font-size:8pt;\"> Accompany it with the complete corresponding machine-readable source code, which must be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or, </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">b)</span><span style=\" font-size:8pt;\"> Accompany it with a written offer, valid for at least three years, to give any third party, for a charge no more than your cost of physically performing source distribution, a complete machine-readable copy of the corresponding source code, to be distributed under the terms of Sections 1 and 2 above on a medium customarily used for software interchange; or, </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:8px; margin-left:30px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">c)</span><span style=\" font-size:8pt;\"> Accompany it with the information you received as to the offer to distribute corresponding source code. (This alternative is allowed only for noncommercial distribution and only if you received the program in object code or executable form with such an offer, in accord with Subsection b above.) </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The source code for a work means the preferred form of the work for making modifications to it. For an executable work, complete source code means all the source code for all modules it contains, plus any associated interface definition files, plus the scripts used to control compilation and installation of the executable. However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, unless that component itself accompanies the executable. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If distribution of executable or object code is made by offering access to copy from a designated place, then offering equivalent access to copy the source code from the same place counts as distribution of the source code, even though third parties are not compelled to copy the source along with the object code. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">4.</span><span style=\" font-size:8pt;\"> You may not copy, modify, sublicense, or distribute the Program except as expressly provided under this License. Any attempt otherwise to copy, modify, sublicense or distribute the Program is void, and will automatically terminate your rights under this License. However, parties who have received copies, or rights, from you under this License will not have their licenses terminated so long as such parties remain in full compliance. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">5.</span><span style=\" font-size:8pt;\"> You are not required to accept this License, since you have not signed it. However, nothing else grants you permission to modify or distribute the Program or its derivative works. These actions are prohibited by law if you do not accept this License. Therefore, by modifying or distributing the Program (or any work based on the Program), you indicate your acceptance of this License to do so, and all its terms and conditions for copying, distributing or modifying the Program or works based on it. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">6.</span><span style=\" font-size:8pt;\"> Each time you redistribute the Program (or any work based on the Program), the recipient automatically receives a license from the original licensor to copy, distribute or modify the Program subject to these terms and conditions. You may not impose any further restrictions on the recipients\' exercise of the rights granted herein. You are not responsible for enforcing compliance by third parties to this License. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">7.</span><span style=\" font-size:8pt;\"> If, as a consequence of a court judgment or allegation of patent infringement or for any other reason (not limited to patent issues), conditions are imposed on you (whether by court order, agreement or otherwise) that contradict the conditions of this License, they do not excuse you from the conditions of this License. If you cannot distribute so as to satisfy simultaneously your obligations under this License and any other pertinent obligations, then as a consequence you may not distribute the Program at all. For example, if a patent license would not permit royalty-free redistribution of the Program by all those who receive copies directly or indirectly through you, then the only way you could satisfy both it and this License would be to refrain entirely from distribution of the Program. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">If any portion of this section is held invalid or unenforceable under any particular circumstance, the balance of the section is intended to apply and the section as a whole is intended to apply in other circumstances. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">It is not the purpose of this section to induce you to infringe any patents or other property right claims or to contest validity of any such claims; this section has the sole purpose of protecting the integrity of the free software distribution system, which is implemented by public license practices. Many people have made generous contributions to the wide range of software distributed through that system in reliance on consistent application of that system; it is up to the author/donor to decide if he or she is willing to distribute software through any other system and a licensee cannot impose that choice. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This section is intended to make thoroughly clear what is believed to be a consequence of the rest of this License. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">8.</span><span style=\" font-size:8pt;\"> If the distribution and/or use of the Program is restricted in certain countries either by patents or by copyrighted interfaces, the original copyright holder who places the Program under this License may add an explicit geographical distribution limitation excluding those countries, so that distribution is permitted only in or among countries not thus excluded. In such case, this License incorporates the limitation as if written in the body of this License. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">9.</span><span style=\" font-size:8pt;\"> The Free Software Foundation may publish revised and/or new versions of the General Public License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Each version is given a distinguishing version number. If the Program specifies a version number of this License which applies to it and &quot;any later version&quot;, you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">10.</span><span style=\" font-size:8pt;\"> If you wish to incorporate parts of the Program into other free programs whose distribution conditions are different, write to the author to ask for permission. For software which is copyrighted by the Free Software Foundation, write to the Free Software Foundation; we sometimes make exceptions for this. Our decision will be guided by the two goals of preserving the free status of all derivatives of our free software and of promoting the sharing and reuse of software generally. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">NO WARRANTY</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">11.</span><span style=\" font-size:8pt;\"> BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM &quot;AS IS&quot; WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">12.</span><span style=\" font-size:8pt;\"> IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">END OF TERMS AND CONDITIONS</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; font-weight:600;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), QtGui.QApplication.translate("DialogImg2Epub", "About", None, QtGui.QApplication.UnicodeUTF8))

import img2epub_rc
